global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'etl-host'

  - job_name: 'statsd-airflow'
    static_configs:
      - targets: ['statsd-exporter:9102']

  - job_name: 'fastapi'
    static_configs:
      - targets: ['etl-fastapi:8000']
    metrics_path: '/metrics'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-airflow:5432']