# Generated by Django 5.0.4 on 2026-03-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_nom_alter_user_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entreprise',
            field=models.CharField(default='Numeryx', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='fonction',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
