# Generated by Django 5.0.4 on 2026-03-25 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_entreprise_user_fonction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='entreprise',
        ),
    ]
