"""add creation and update dates

Revision ID: ec5102d65ff5
Revises: 
Create Date: 2026-05-19 16:28:03.802828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec5102d65ff5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_behavior_features',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('full_visitor_id', sa.String(length=64), nullable=False),
    sa.Column('nombre_sessions', sa.Integer(), nullable=False),
    sa.Column('total_pageviews', sa.Float(), nullable=False),
    sa.Column('avg_pageviews_per_session', sa.Float(), nullable=False),
    sa.Column('total_hits', sa.Float(), nullable=False),
    sa.Column('avg_hits_per_session', sa.Float(), nullable=False),
    sa.Column('total_bounces', sa.Float(), nullable=False),
    sa.Column('bounce_rate', sa.Float(), nullable=False),
    sa.Column('total_time_on_site', sa.Float(), nullable=False),
    sa.Column('avg_time_on_site', sa.Float(), nullable=False),
    sa.Column('first_visit_date', sa.Date(), nullable=True),
    sa.Column('last_visit_date', sa.Date(), nullable=True),
    sa.Column('days_since_last_visit', sa.Integer(), nullable=False),
    sa.Column('recency_score', sa.Float(), nullable=False),
    sa.Column('suspicious_activity', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_visitor_id', name='uq_lead_behavior_features_visitor')
    )
    op.create_index(op.f('ix_lead_behavior_features_full_visitor_id'), 'lead_behavior_features', ['full_visitor_id'], unique=False)
    op.create_index(op.f('ix_lead_behavior_features_last_visit_date'), 'lead_behavior_features', ['last_visit_date'], unique=False)
    op.create_table('lead_notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('full_visitor_id', sa.String(length=64), nullable=False),
    sa.Column('notification_type', sa.String(length=60), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('old_score', sa.Float(), nullable=True),
    sa.Column('new_score', sa.Float(), nullable=True),
    sa.Column('old_segment', sa.String(length=12), nullable=True),
    sa.Column('new_segment', sa.String(length=12), nullable=True),
    sa.Column('last_visit_date', sa.Date(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_visitor_id', 'notification_type', 'last_visit_date', name='uq_lead_notifications_daily_type')
    )
    op.create_index(op.f('ix_lead_notifications_full_visitor_id'), 'lead_notifications', ['full_visitor_id'], unique=False)
    op.create_index(op.f('ix_lead_notifications_last_visit_date'), 'lead_notifications', ['last_visit_date'], unique=False)
    op.create_table('lead_scores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('full_visitor_id', sa.String(length=64), nullable=False),
    sa.Column('lead_score', sa.Float(), nullable=False),
    sa.Column('lead_score_100', sa.Float(), nullable=False),
    sa.Column('segment', sa.String(length=12), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=False),
    sa.Column('nombre_sessions_raw', sa.Float(), nullable=False),
    sa.Column('avg_hits_per_session_raw', sa.Float(), nullable=False),
    sa.Column('avg_pageviews_per_session_raw', sa.Float(), nullable=False),
    sa.Column('bounce_rate_raw', sa.Float(), nullable=False),
    sa.Column('recency_score_raw', sa.Float(), nullable=False),
    sa.Column('nombre_sessions_scaled', sa.Float(), nullable=False),
    sa.Column('avg_hits_per_session_scaled', sa.Float(), nullable=False),
    sa.Column('avg_pageviews_per_session_scaled', sa.Float(), nullable=False),
    sa.Column('bounce_score', sa.Float(), nullable=False),
    sa.Column('suspicious_activity', sa.Integer(), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_visitor_id', name='uq_lead_scores_visitor')
    )
    op.create_index(op.f('ix_lead_scores_full_visitor_id'), 'lead_scores', ['full_visitor_id'], unique=False)
    op.create_table('lead_sessions_raw',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('full_visitor_id', sa.String(length=64), nullable=False),
    sa.Column('visit_id', sa.BigInteger(), nullable=True),
    sa.Column('session_id', sa.String(length=160), nullable=False),
    sa.Column('visit_number', sa.Integer(), nullable=True),
    sa.Column('visit_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('visit_hour', sa.Integer(), nullable=True),
    sa.Column('device_category', sa.String(length=80), nullable=True),
    sa.Column('browser', sa.String(length=160), nullable=True),
    sa.Column('operating_system', sa.String(length=160), nullable=True),
    sa.Column('country', sa.String(length=160), nullable=True),
    sa.Column('city', sa.String(length=160), nullable=True),
    sa.Column('traffic_source', sa.String(length=255), nullable=True),
    sa.Column('totals_pageviews', sa.Integer(), nullable=False),
    sa.Column('totals_hits', sa.Integer(), nullable=False),
    sa.Column('totals_bounces', sa.Integer(), nullable=False),
    sa.Column('total_time_on_site', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', name='uq_lead_sessions_raw_session_id')
    )
    op.create_index(op.f('ix_lead_sessions_raw_full_visitor_id'), 'lead_sessions_raw', ['full_visitor_id'], unique=False)
    op.create_index(op.f('ix_lead_sessions_raw_visit_date'), 'lead_sessions_raw', ['visit_date'], unique=False)
    op.create_table('leads_activity',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('full_visitor_id', sa.String(length=64), nullable=False),
    sa.Column('visit_id', sa.BigInteger(), nullable=True),
    sa.Column('session_id', sa.String(length=160), nullable=False),
    sa.Column('visit_number', sa.Integer(), nullable=True),
    sa.Column('visit_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('visit_hour', sa.Integer(), nullable=True),
    sa.Column('device_category', sa.String(length=80), nullable=True),
    sa.Column('browser', sa.String(length=160), nullable=True),
    sa.Column('operating_system', sa.String(length=160), nullable=True),
    sa.Column('country', sa.String(length=160), nullable=True),
    sa.Column('city', sa.String(length=160), nullable=True),
    sa.Column('traffic_source', sa.String(length=255), nullable=True),
    sa.Column('totals_pageviews', sa.Integer(), nullable=False),
    sa.Column('totals_hits', sa.Integer(), nullable=False),
    sa.Column('totals_bounces', sa.Integer(), nullable=False),
    sa.Column('total_time_on_site', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', name='uq_leads_activity_session_id')
    )
    op.create_index(op.f('ix_leads_activity_full_visitor_id'), 'leads_activity', ['full_visitor_id'], unique=False)
    op.create_index(op.f('ix_leads_activity_visit_date'), 'leads_activity', ['visit_date'], unique=False)
    op.add_column('potential_linkedin', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('potential_linkedin', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('potential_linkedin', 'updated_at')
    op.drop_column('potential_linkedin', 'created_at')
    op.drop_index(op.f('ix_leads_activity_visit_date'), table_name='leads_activity')
    op.drop_index(op.f('ix_leads_activity_full_visitor_id'), table_name='leads_activity')
    op.drop_table('leads_activity')
    op.drop_index(op.f('ix_lead_sessions_raw_visit_date'), table_name='lead_sessions_raw')
    op.drop_index(op.f('ix_lead_sessions_raw_full_visitor_id'), table_name='lead_sessions_raw')
    op.drop_table('lead_sessions_raw')
    op.drop_index(op.f('ix_lead_scores_full_visitor_id'), table_name='lead_scores')
    op.drop_table('lead_scores')
    op.drop_index(op.f('ix_lead_notifications_last_visit_date'), table_name='lead_notifications')
    op.drop_index(op.f('ix_lead_notifications_full_visitor_id'), table_name='lead_notifications')
    op.drop_table('lead_notifications')
    op.drop_index(op.f('ix_lead_behavior_features_last_visit_date'), table_name='lead_behavior_features')
    op.drop_index(op.f('ix_lead_behavior_features_full_visitor_id'), table_name='lead_behavior_features')
    op.drop_table('lead_behavior_features')
    # ### end Alembic commands ###
