FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install prometheus-fastapi-instrumentator psutil


CMD ["uvicorn", "apis.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]