FROM apache/airflow:3.0.0

USER root
COPY requirements.airflow.txt /requirements.airflow.txt
USER airflow

RUN pip install --no-cache-dir \
    --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-3.0.0/constraints-3.12.txt" \
    -r /requirements.airflow.txt