"""ajout de colonne status

Revision ID: 485b356c7293
Revises: 9b9d3af371ba
Create Date: 2026-04-11 23:48:42.553420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '485b356c7293'
down_revision: Union[str, None] = '9b9d3af371ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entreprise', sa.Column('statut', sa.String(), nullable=True))
    op.alter_column('entreprise', 'code_postal',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entreprise', 'code_postal',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('entreprise', 'statut')
    # ### end Alembic commands ###
