"""ajout de colonne taux_completude

Revision ID: 9b9d3af371ba
Revises: d7442c7d849e
Create Date: 2026-04-10 09:13:57.454796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b9d3af371ba'
down_revision: Union[str, None] = 'd7442c7d849e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entreprise', sa.Column('taux_completude', sa.Float(), nullable=True))
    op.drop_constraint('uq_entreprise_nom_cp', 'entreprise', type_='unique')
    op.drop_constraint('uq_entreprise_siren', 'entreprise', type_='unique')
    op.drop_constraint('uq_entreprise_siret', 'entreprise', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_entreprise_siret', 'entreprise', ['siret'])
    op.create_unique_constraint('uq_entreprise_siren', 'entreprise', ['siren'])
    op.create_unique_constraint('uq_entreprise_nom_cp', 'entreprise', ['nom', 'code_postal'])
    op.drop_column('entreprise', 'taux_completude')
    # ### end Alembic commands ###
