"""fix_entreprise_constraints

Revision ID: d7442c7d849e
Revises: 75a679743ec9
Create Date: 2026-04-09 23:08:41.567255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7442c7d849e'
down_revision: Union[str, None] = '75a679743ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entreprise_siren', table_name='entreprise')
    op.create_index(op.f('ix_entreprise_siren'), 'entreprise', ['siren'], unique=True)
    op.drop_index('ix_entreprise_siret', table_name='entreprise')
    op.create_index(op.f('ix_entreprise_siret'), 'entreprise', ['siret'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entreprise_siret'), table_name='entreprise')
    op.create_index('ix_entreprise_siret', 'entreprise', ['siret'], unique=False)
    op.drop_index(op.f('ix_entreprise_siren'), table_name='entreprise')
    op.create_index('ix_entreprise_siren', 'entreprise', ['siren'], unique=False)
    # ### end Alembic commands ###
