FROM python:3.10-slim

WORKDIR /app

ENV PIP_DEFAULT_TIMEOUT=1000 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

COPY requirements.txt .
RUN pip install --upgrade pip \
    && pip install --no-cache-dir --retries 10 -r requirements.txt


CMD ["uvicorn", "apis.main:app", "--host", "0.0.0.0", "--port", "8002", "--reload"]
